### ISSUE TITLE
Lab1 review

### ISSUE THREAD

**Issue by francescoscalera99** [lorenzobellino/Computational-Intelligence-2022#3]
Hey Lorenzo!
First of all, I want to tell you that I really appreciate the completeness and readability of Readme: it helped me a lot to understand your choices and your implementation. 
### MAJOR
- I agree with you about the fact that a greedy strategy could be the best tradeoff between amount of computation time and a reasonable (maybe not optimal) solution, especially with larger values of N. But when you facing the problem for N<=20, other implementations (like A* search) allow us to find an optimal solution without a huge amount of computation. 

###MINOR
- You can try to speed up your search, in general, by removing duplicates of the elements of the initial list of lists, and remove the list who are empty.

**Comment by lorenzobellino** [comment]
Thank's for the suggestions! 
I added a new file implementing a vanilla version of **Dijkstra's algorithm** in order to find a globally optimal solution for values of $N <= 20$, maybe in the future i will try to implement a version of **A\***.
I also updated my original code in order to speed up my search as you suggested removing duplicates and empty list.
I will close this Issue but if you have more suggestion feel free to open a new one.
